// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizAPI.Models;

#nullable disable

namespace QuizAPI.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizAPI.Models.Partipicant", b =>
                {
                    b.Property<string>("PartipicantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TimeTaken")
                        .HasColumnType("int");

                    b.HasKey("PartipicantId");

                    b.ToTable("Participations");

                    b.HasData(
                        new
                        {
                            PartipicantId = "ASD",
                            Email = "prtpcnt1@gmail.com",
                            Name = "P1",
                            Score = 3,
                            TimeTaken = 500
                        });
                });

            modelBuilder.Entity("QuizAPI.Models.Question", b =>
                {
                    b.Property<int>("QnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QnId"));

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QnInWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QnId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QnId = 1,
                            Answer = 2,
                            ImageName = "",
                            Option1 = "Hyper Trainer Marking Language",
                            Option2 = "Hyper Text Marketing Language",
                            Option3 = "Hyper Text Markup Leveler",
                            Option4 = "Hyper Text Markup Language",
                            QnInWords = "What does HTML stand for?"
                        },
                        new
                        {
                            QnId = 2,
                            Answer = 2,
                            ImageName = "",
                            Option1 = "ALU",
                            Option2 = "Memory",
                            Option3 = "CPU",
                            Option4 = "Control Unit",
                            QnInWords = "The brain of any computer system is"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
